#
# Release workflow
#
name: Release

on:
  # tagged manually
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  # dispatch from tagpr.yaml workflow
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ~1.19
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
